using System;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Win32;

namespace Mizar.WebInstaller {
  public sealed class FreshInstallResult {
    internal FreshInstallResult(string directory) { Directory = directory; CoreInstalled = true; }
    public string Directory { get; private set; }
    public Task RollbackAsync() { return Nsis.RollbackOwnedFresh(Directory, TimeSpan.FromMinutes(10)); }
    // Core installation is never the Core + default resource completion signal.
    public bool CoreInstalled { get; private set; }
    public bool ResourcesReady { get { return false; } }
  }
  public sealed class InstallerRecoveryRequired : IOException {
    public readonly string InstallDirectory;
    public InstallerRecoveryRequired(string directory, string reason) : base(reason) { InstallDirectory = directory; }
  }
  public static class Nsis {
    static void ValidateDestination(string directory) {
      string target = Path.GetFullPath(directory);
      string local = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Programs") + Path.DirectorySeparatorChar;
      string qualification = Path.Combine(Path.GetTempPath(), "Mizar-WebInstaller-Qualification") + Path.DirectorySeparatorChar;
      if ((!(target.StartsWith(local, StringComparison.OrdinalIgnoreCase) || target.StartsWith(qualification, StringComparison.OrdinalIgnoreCase))) ||
          target.IndexOfAny(new char[] { '"', '\r', '\n' }) >= 0)
        throw new IOException("安装位置不受允许。");
      Downloader.NoReparse(target);
      if (Directory.Exists(target) || File.Exists(target)) throw new IOException("安装位置已存在，请使用既有更新或修复入口。");
      using (var key = Registry.CurrentUser.OpenSubKey(@"Software\Mizar"))
        if (key != null) throw new IOException("检测到已有 Mizar，请使用应用内更新。");
      using (var key = Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\Mizar"))
        if (key != null) throw new IOException("检测到已有 Mizar 安装登记。");
      if (Directory.Exists(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.StartMenu), "Programs", "Mizar")) ||
          File.Exists(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory), "Mizar.lnk")))
        throw new IOException("检测到已有 Mizar 快捷方式，请先使用原安装器修复。");
      if (Process.GetProcessesByName("Mizar").Length != 0) throw new IOException("请正常退出 Mizar 后再安装。");
    }
    static async Task<int> Wait(Process child, TimeSpan deadline, Action cancelling, CancellationToken token) {
      var clock = Stopwatch.StartNew(); bool notified = false;
      while (!child.HasExited) {
        if (token.IsCancellationRequested && !notified) {
          notified = true; if (cancelling != null) cancelling();
          // Never terminate a writer in the middle of NSIS extraction. Cancellation
          // becomes rollback after the existing installer has safely stopped.
        }
        if (clock.Elapsed >= deadline) throw new TimeoutException("安装程序尚未退出；保留现场，禁止并发重试。");
        await Task.Delay(100).ConfigureAwait(false);
      }
      return child.ExitCode;
    }
    static void AssertOwnedRegistration(string target) {
      using (var uninstall = Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall\Mizar")) {
        if (uninstall != null && Convert.ToString(uninstall.GetValue("UninstallString")) != "\"" + Path.Combine(target, "Uninstall.exe") + "\"")
          throw new IOException("卸载登记已被其他安装更改，保留现场供修复。");
      }
      using (var key = Registry.CurrentUser.OpenSubKey(@"Software\Mizar")) {
        if (key != null && !String.Equals(Path.GetFullPath(Convert.ToString(key.GetValue("InstallDir"))), target, StringComparison.OrdinalIgnoreCase))
          throw new IOException("安装登记已被其他安装更改，保留现场供修复。");
      }
    }
    internal static async Task RollbackOwnedFresh(string target, TimeSpan deadline) {
      target = Path.GetFullPath(target); Downloader.NoReparse(target); AssertOwnedRegistration(target);
      string uninstaller = Path.Combine(target, "Uninstall.exe"); Downloader.NoReparse(uninstaller);
      if (!File.Exists(uninstaller)) {
        if (!Directory.Exists(target)) return;
        throw new InstallerRecoveryRequired(target, "未生成原卸载器，保留未完成安装供修复。");
      }
      // This is the existing uninstaller generated by the authenticated NSIS into
      // the newly owned directory. Keep it locked against replacement while running.
      using (var locked = new FileStream(uninstaller, FileMode.Open, FileAccess.Read, FileShare.Read))
      using (var child = Process.Start(new ProcessStartInfo {
        FileName = uninstaller, Arguments = "/S _?=" + target,
        UseShellExecute = false, CreateNoWindow = true, WorkingDirectory = target,
      })) {
        if (await Wait(child, deadline, null, CancellationToken.None) != 0)
          throw new InstallerRecoveryRequired(target, "原卸载器未完成，保留现场供修复。");
      }
      // _?= runs in place, so Windows may keep the generated uninstaller itself.
      if (File.Exists(uninstaller)) File.Delete(uninstaller);
      if (Directory.Exists(target) && Directory.GetFileSystemEntries(target).Length == 0) Directory.Delete(target);
      AssertOwnedRegistration(target);
      using (var key = Registry.CurrentUser.OpenSubKey(@"Software\Mizar"))
        if (key != null) throw new InstallerRecoveryRequired(target, "安装登记未清理。");
      // No recursive delete: NSIS alone owns payload removal; user assets remain outside.
      if (Directory.Exists(target) && Directory.GetFileSystemEntries(target).Length != 0)
        throw new InstallerRecoveryRequired(target, "仍有文件残留，保留现场供修复。");
    }
    public static async Task<FreshInstallResult> Install(Plan plan, string installer, string destination,
      CancellationToken token, Action cancelling = null, TimeSpan? deadline = null) {
      plan.Validate();
      if (!plan.allowExecute || plan.kind != "nsis-setup") throw new IOException("缺少固定安装授权。");
      installer = Path.GetFullPath(installer); destination = Path.GetFullPath(destination);
      Downloader.NoReparse(installer); ValidateDestination(destination); token.ThrowIfCancellationRequested();
      string leaseDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Mizar", "bootstrap-cache");
      Downloader.NoReparse(leaseDirectory); Directory.CreateDirectory(leaseDirectory);
      string leasePath = Path.Combine(leaseDirectory, "fresh-install.lock"); Downloader.NoReparse(leasePath);
      // File leases survive async continuations without thread-owned Mutex semantics.
      using (var lease = new FileStream(leasePath, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None)) {
          ValidateDestination(destination);
          using (var locked = new FileStream(installer, FileMode.Open, FileAccess.Read, FileShare.Read, 65536, true)) {
            if (!await Downloader.MatchesStream(locked, plan, token)) throw new IOException("安装文件已变化。");
            token.ThrowIfCancellationRequested();
            int code;
            using (var child = Process.Start(new ProcessStartInfo {
              FileName = installer, Arguments = "/S /MIZARUPDATE /D=" + destination,
              UseShellExecute = false, CreateNoWindow = true, WorkingDirectory = Path.GetDirectoryName(installer),
            })) {
              try { code = await Wait(child, deadline ?? TimeSpan.FromMinutes(10), cancelling, token); }
              catch (TimeoutException error) { throw new InstallerRecoveryRequired(destination, error.Message); }
            }
            if (code != 0 || token.IsCancellationRequested) {
              await RollbackOwnedFresh(destination, deadline ?? TimeSpan.FromMinutes(10));
              token.ThrowIfCancellationRequested(); throw new IOException("核心安装未完成，原卸载器已清理本次安装。");
            }
            try {
              AssertOwnedRegistration(destination);
              if (!File.Exists(Path.Combine(destination, "installed.flag"))) throw new IOException("核心安装未完成。");
              var json = new System.Web.Script.Serialization.JavaScriptSerializer();
              var artifact = json.Deserialize<System.Collections.Generic.Dictionary<string, object>>(File.ReadAllText(Path.Combine(destination, "resources", "metadata", "artifact.json")));
              if (Convert.ToString(artifact["repository"]) != "Starfie1d1272/Mizar" || Convert.ToString(artifact["appVersion"]) != plan.version ||
                  Convert.ToString(artifact["gitSha"]) != plan.gitSha || Convert.ToString(artifact["artifactSha256"]) != plan.contentDigest)
                throw new IOException("安装后的核心身份不匹配。");
            } catch {
              await RollbackOwnedFresh(destination, deadline ?? TimeSpan.FromMinutes(10)); throw;
            }
            return new FreshInstallResult(destination);
          }
      }
    }
  }
}
