fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "restore_layout",
            "restore_cs2_focus",
            "set_program_overlay_enabled",
            "cs2_host_status",
            "select_obs_executable",
            "launch_obs",
            "cs2_config_status",
            "start_managed_cs2",
            "finish_managed_cs2",
            "restore_cs2_backup",
            "open_cs2_backup",
            "set_cs2_preferences",
            "open_main",
            "present_production",
            "open_tool",
            "open_rivalhub_authorization",
            "open_rivalhub_workbench",
            "open_steam_api_key",
            "open_issue_report",
            "save_support_bundle",
            "gsi_status",
            "ensure_gsi",
            "configure_gsi",
            "select_cs2_installation",
            "open_cs2_config_directory",
        ]),
    ))
    .expect("Tauri build metadata");
}
