[package]
name = "mizar-desktop"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "=2.11.6", features = ["tray-icon"] }
tauri-runtime = "=2.11.3"
tauri-runtime-wry = "=2.11.4"
tauri-utils = "=2.9.3"
tauri-macros = "=2.6.3"
serde_json = "1.0"
tauri-plugin-dialog = "=2.7.3"

[build-dependencies]
tauri-build = "=2.6.3"

[profile.release]
strip = true
lto = true
codegen-units = 1

[profile.ci]
inherits = "release"
opt-level = 1
lto = false
codegen-units = 16
strip = true
